# xrp-ledger.toml for multiple tokens

[[CURRENCIES]]
code = "TESTBEST1"
issuer = "rBSRJkUPSWCkCWicQ95aY5SYTCZzJv2mXK"
name = "Token best 1"
desc = "This is the first token for my project."
website = "https://example.com/token1"
twitter = "https://twitter.com/YourToken1Handle"
telegram = "https://t.me/YourToken1Channel"

[[CURRENCIES]]
code = "TOKEN2"
issuer = "rEXAMPLEISSUER"
name = "Token Two"
desc = "This is the second token for my project."
website = "https://example.com/token2"
twitter = "https://twitter.com/YourToken2Handle"
telegram = "https://t.me/YourToken2Channel"
